
import time
import datetime
import logging
import configparser
import tradehull
import pandas as pd
import databasemanager 

class DataUpdater:
    def __init__(self, api_key, secret_key, watchlist):
        self.api_key = api_key
        self.secret_key = secret_key
        self.watchlist = watchlist
        self.TH = tradehull.Tradehull(api_key, secret_key, "yes")
        self.kite = self.TH.kite
        self.kws = self.TH.kws
        self.instrument = self.TH.instrument_file
        self.token_list = self._get_token_list()

        self.db_manager = databasemanager.DatabaseManager()

    def _get_token_list(self):
        token_list = self.instrument.loc[self.instrument['tradingsymbol'].isin(self.watchlist) == True]['instrument_token'].tolist()
        return token_list

    def on_ticks(self, ws, ticks):
        print('New tick at: ', datetime.datetime.now())
        logging.debug("Ticks: {}".format(ticks))
        self.db_manager.update_data(datetime.datetime.now(), ticks)

    def on_connect(self, ws, response):
        ws.subscribe(self.token_list)

    def on_close(self, ws, code, reason):
        ws.stop()

    def run(self):
        self.kws.on_ticks = self.on_ticks
        self.kws.on_connect = self.on_connect
        self.kws.on_close = self.on_close
        self.kws.connect()

if __name__ == "__main__":
    config = configparser.ConfigParser()
    config.read('config.ini')

    api_key = config.get('API', 'api_key')
    secret_key = config.get('API', 'secret_key')

    watchlist = ["NIFTY23JULFUT","BANKNIFTY23JULFUT","AARTIIND23JULFUT","ABB23JULFUT","ABBOTINDIA23JULFUT","ABCAPITAL23JULFUT","ABFRL23JULFUT","ACC23JULFUT","ADANIENT23JULFUT","ADANIPORTS23JULFUT","ALKEM23JULFUT","AMBUJACEM23JULFUT","APOLLOHOSP23JULFUT","APOLLOTYRE23JULFUT","ASHOKLEY23JULFUT","ASIANPAINT23JULFUT","ASTRAL23JULFUT","ATUL23JULFUT","AUBANK23JULFUT","AUROPHARMA23JULFUT","AXISBANK23JULFUT","BAJAJ-AUTO23JULFUT","BAJAJFINSV23JULFUT","BAJFINANCE23JULFUT","BALKRISIND23JULFUT","BALRAMCHIN23JULFUT","BANDHANBNK23JULFUT","BANKBARODA23JULFUT","BATAINDIA23JULFUT","BEL23JULFUT","BERGEPAINT23JULFUT","BHARATFORG23JULFUT","BHARTIARTL23JULFUT","BHEL23JULFUT","BIOCON23JULFUT","BOSCHLTD23JULFUT","BPCL23JULFUT","BRITANNIA23JULFUT","BSOFT23JULFUT","CANBK23JULFUT","CANFINHOME23JULFUT","CHAMBLFERT23JULFUT","CHOLAFIN23JULFUT","CIPLA23JULFUT","COALINDIA23JULFUT","COFORGE23JULFUT","COLPAL23JULFUT","CONCOR23JULFUT","COROMANDEL23JULFUT","CROMPTON23JULFUT","CUB23JULFUT","CUMMINSIND23JULFUT","DABUR23JULFUT","DALBHARAT23JULFUT","DEEPAKNTR23JULFUT","DELTACORP23JULFUT","DIVISLAB23JULFUT","DIXON23JULFUT","DLF23JULFUT","DRREDDY23JULFUT","EICHERMOT23JULFUT","ESCORTS23JULFUT","EXIDEIND23JULFUT","FEDERALBNK23JULFUT","GAIL23JULFUT","GLENMARK23JULFUT","GMRINFRA23JULFUT","GNFC23JULFUT","GODREJCP23JULFUT","GODREJPROP23JULFUT","GRANULES23JULFUT","GRASIM23JULFUT","GUJGASLTD23JULFUT","HAL23JULFUT","HAVELLS23JULFUT","HCLTECH23JULFUT","HDFCAMC23JULFUT","HDFCBANK23JULFUT","HDFCLIFE23JULFUT","HEROMOTOCO23JULFUT","HINDALCO23JULFUT","HINDCOPPER23JULFUT","HINDPETRO23JULFUT","HINDUNILVR23JULFUT","IBULHSGFIN23JULFUT","ICICIBANK23JULFUT","ICICIGI23JULFUT","ICICIPRULI23JULFUT","IDEA23JULFUT","IDFC23JULFUT","IDFCFIRSTB23JULFUT","IEX23JULFUT","IGL23JULFUT","INDHOTEL23JULFUT","INDIACEM23JULFUT","INDIAMART23JULFUT","INDIGO23JULFUT","INDUSINDBK23JULFUT","INDUSTOWER23JULFUT","INFY23JULFUT","INTELLECT23JULFUT","IOC23JULFUT","IPCALAB23JULFUT","IRCTC23JULFUT","ITC23JULFUT","JINDALSTEL23JULFUT","JKCEMENT23JULFUT","JSWSTEEL23JULFUT","JUBLFOOD23JULFUT","KOTAKBANK23JULFUT","L&TFH23JULFUT","LALPATHLAB23JULFUT","LAURUSLABS23JULFUT","LICHSGFIN23JULFUT","LT23JULFUT","LTIM23JULFUT","LTTS23JULFUT","LUPIN23JULFUT","M&M23JULFUT","M&MFIN23JULFUT","MANAPPURAM23JULFUT","MARICO23JULFUT","MARUTI23JULFUT","MCDOWELL-N23JULFUT","MCX23JULFUT","METROPOLIS23JULFUT","MFSL23JULFUT","MGL23JULFUT","MOTHERSON23JULFUT","MPHASIS23JULFUT","MRF23JULFUT","MUTHOOTFIN23JULFUT","NATIONALUM23JULFUT","NAUKRI23JULFUT","NAVINFLUOR23JULFUT","NESTLEIND23JULFUT","NMDC23JULFUT","NTPC23JULFUT","OBEROIRLTY23JULFUT","OFSS23JULFUT","ONGC23JULFUT","PAGEIND23JULFUT","PEL23JULFUT","PERSISTENT23JULFUT","PETRONET23JULFUT","PFC23JULFUT","PIDILITIND23JULFUT","PIIND23JULFUT","PNB23JULFUT","POLYCAB23JULFUT","POWERGRID23JULFUT","PVRINOX23JULFUT","RAMCOCEM23JULFUT","RBLBANK23JULFUT","RECLTD23JULFUT","RELIANCE23JULFUT","SAIL23JULFUT","SBICARD23JULFUT","SBILIFE23JULFUT","SBIN23JULFUT","SHREECEM23JULFUT","SHRIRAMFIN23JULFUT","SIEMENS23JULFUT","SRF23JULFUT","SUNPHARMA23JULFUT","SUNTV23JULFUT","SYNGENE23JULFUT","TATACHEM23JULFUT","TATACOMM23JULFUT","TATACONSUM23JULFUT","TATAMOTORS23JULFUT","TATAPOWER23JULFUT","TATASTEEL23JULFUT","TCS23JULFUT","TECHM23JULFUT","TITAN23JULFUT","TORNTPHARM23JULFUT","TRENT23JULFUT","TVSMOTOR23JULFUT","UBL23JULFUT","ULTRACEMCO23JULFUT","UPL23JULFUT","VEDL23JULFUT","VOLTAS23JULFUT","WIPRO23JULFUT","ZEEL23JULFUT","ZYDUSLIFE23JULFUT"]

        # Add the list of financial instruments here
    

    data_updater = DataUpdater(api_key, secret_key, watchlist)
    data_updater.run()
